package feedstore

const FEED_STATUS_ACTIVE = "active"
const FEED_STATUS_INACTIVE = "inactive"
const LINK_STATUS_ACTIVE = "active"
const LINK_STATUS_INACTIVE = "inactive"

const COLUMN_CHECKED_AT = "checked_at"
const COLUMN_CREATED_AT = "created_at"
const COLUMN_ID = "id"
const COLUMN_DESCRIPTION = "description"
const COLUMN_FEED_ID = "feed_id"
const COLUMN_FETCH_INTERVAL = "fetch_interval"
const COLUMN_LAST_FETCHED_AT = "last_fetched_at"
const COLUMN_MEMO = "memo"
const COLUMN_NAME = "name"
const COLUMN_REPORTED_AT = "reported_at"
const COLUMN_STATUS = "status"
const COLUMN_SOFT_DELETED_AT = "soft_deleted_at"
const COLUMN_TIME = "time"
const COLUMN_TITLE = "title"
const COLUMN_UPDATED_AT = "updated_at"
const COLUMN_URL = "url"
const COLUMN_VOTES_DOWN = "votes_down"
const COLUMN_VOTES_UP = "votes_up"
const COLUMN_VIEWS = "views"
const COLUMN_REPORT = "report"
